language: ruby
rvm:
- 2.4.1
before_script:
- chmod +x ./script/cibuild
branches:
  only:
  - gh-pages
  - "/pages-(.*)/"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
addons:
  apt:
    packages:
    - libcurl14-openssl-dev
sudo: false
cache: bundler
notifications:
  slack:
    secure: aisAnkAjH0FrCy3pvxrfavo10nhiv0hVUbBHH+ULKom8wu0z3KJHPDN6yreRhqLeko1l2UcCu6qzsTndjDtKLVRS66eUlCXBfc4emOJl747VafOzl/jlT3EUujp+4t2/lHtEcwmt7lXP3ca6XvwbzrvH4bHi5wrU/ne6y17MgQryKeTBp6cDPRAHVpluHvBGdHawNHpzhk3nOh4CG+8Rq0TW/cRKWv+If5OaUHEldwnxhYIqiL2kOlQpzHz4AaDYtssMOcbxHXUAdC1kU209Dj49F4yReGrGVEq1cDYsrs1vOsHwMIjTZVKCdYKB+IEbpsCnjseBsppvDYabShfumO78Va8Dn3I+JhlGyBYTlady7HLAKh7885qYEw2C80l4/imNnVxIehhIiRCCY8sPKjTwMZ6vqCWmnkjcpFIXrlZhxmWyVfnpb9k8quAxlDEM5ED03eSnQumgTE3GfUPLi4j3g4xU8vu7nElH3fIpMQQB5X/tfVOby+x0xKjbGENYTK162Bph0mo8Qt4OCSBmsEbzl/a6ZWiIlhF1HwfeqLH8XGrX0kISqhmzt9eP5fFh6a8UMGREV9Zc52YT/ZI7HJXC9Gq8BmdG5TKOgVcqi9XTQQ3hoiynKlXbS3SiYAPyMpcrZivdpqiOUYR9RflkfCnhau5mQNpaeV1GjBAEj0I=
